import { env } from "@luke/env/server";
import { drizzle } from "drizzle-orm/node-postgres";

import {
	account,
	accountRelations,
	session,
	sessionRelations,
	user,
	userRelations,
	verification,
} from "./schema/auth";
import {
	assets,
	assetsRelations,
	contractModelCoverage,
	contractPartCoverage,
	contracts,
	contractsRelations,
	engineerClockEvents,
	engineerLocations,
	engineers,
	engineersRelations,
	faultReports,
	fileAttachments,
	geofenceEvents,
	hospitals,
	hospitalsRelations,
	jobCosts,
	jobExpenses,
	jobPartsUsage,
	jobStateEvents,
	jobs,
	jobsRelations,
	jobTimers,
	manualQaQueries,
	nfcEvents,
	nfcTags,
	opportunisticPmAlerts,
	partInventory,
	parts,
	partsShortages,
	productModelParts,
	productModels,
	productModelsRelations,
	pushNotifications,
	reportSnapshots,
	serviceManualSections,
	serviceManuals,
	systemParameters,
	tenantMemberships,
	tenants,
	tenantsRelations,
	websocketEvents,
} from "./schema/service-ops";

export const schema = {
	account,
	accountRelations,
	assets,
	assetsRelations,
	contractModelCoverage,
	contractPartCoverage,
	contracts,
	contractsRelations,
	engineerClockEvents,
	engineerLocations,
	engineers,
	engineersRelations,
	faultReports,
	fileAttachments,
	geofenceEvents,
	hospitals,
	hospitalsRelations,
	jobCosts,
	jobExpenses,
	jobPartsUsage,
	jobs,
	jobsRelations,
	jobStateEvents,
	jobTimers,
	manualQaQueries,
	nfcEvents,
	nfcTags,
	opportunisticPmAlerts,
	partInventory,
	parts,
	partsShortages,
	productModelParts,
	productModels,
	productModelsRelations,
	pushNotifications,
	reportSnapshots,
	serviceManuals,
	serviceManualSections,
	session,
	sessionRelations,
	systemParameters,
	tenantMemberships,
	tenants,
	tenantsRelations,
	user,
	userRelations,
	verification,
	websocketEvents,
};

export function createDb() {
	return drizzle(env.DATABASE_URL, { schema });
}

export const db = createDb();
